services:
  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.9.0
    container_name: wazuh-indexer
    environment:
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
      - cluster.name=wazuh-cluster
      - network.host=0.0.0.0
      - plugins.security.disabled=false
      - plugins.security.ssl.http.enabled=true
      - plugins.security.ssl.http.pemcert_filepath=certs/wazuh-indexer.pem
      - plugins.security.ssl.http.pemkey_filepath=certs/wazuh-indexer-key.pem
      - plugins.security.ssl.http.pemtrustedcas_filepath=certs/root-ca.pem
      - plugins.security.nodes_dn=["CN=wazuh-indexer,OU=Wazuh,O=Wazuh,L=California,C=US"]
      - plugins.security.authcz.admin_dn=["CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"]
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./wazuh/indexer_conf/securityconfig:/usr/share/wazuh-indexer/securityconfig:ro
      - siem_esdata:/var/lib/wazuh-indexer
      - ./wazuh/indexer_conf/opensearch.yml:/usr/share/wazuh-indexer/opensearch.yml:ro
      - ./wazuh/indexer_conf/certs:/usr/share/wazuh-indexer/config/certs:ro
    command: /usr/share/wazuh-indexer/bin/opensearch
    networks:
      - orchestration_net

  wazuh-manager:
    image: wazuh/wazuh-manager:4.9.0
    container_name: wazuh-manager
    restart: always
    ports:
      - "1514:1514"
      - "1515:1515"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://wazuh-indexer:9200
    volumes:
      - ./wazuh/manager_etc:/var/ossec/etc
      - ./wazuh/manager_logs:/var/ossec/logs
      - ./wazuh/manager_conf/ossec.conf:/var/ossec/etc/ossec.conf:ro
    networks:
      - orchestration_net

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.9.0
    container_name: wazuh-dashboard
    hostname: wazuh-dashboard
    user: "0"
    entrypoint: >
      /bin/bash -c "
      export INDEXER_USERNAME=${INDEXER_USERNAME} &&
      export INDEXER_PASSWORD=${INDEXER_PASSWORD} &&
      /usr/share/wazuh-dashboard/bin/opensearch-dashboards --allow-root"
    ports:
      - "5601:5601"
    volumes:
      - ./wazuh/wazuh-certs/wazuh-certifictes:/usr/share/wazuh-dashboard/certs:ro
      - ./wazuh/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml:ro
    networks:
      - orchestration_net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.3
    container_name: logstash
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "5044:5044"
    networks:
      - orchestration_net

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.14.3
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/var/log/host:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - orchestration_net

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wazuh-dashboard
    networks:
      - orchestration_net

volumes:
  siem_esdata:
    driver: local

networks:
  orchestration_net:
    external: true
