services:
  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.9.0
    container_name: wazuh-indexer
    environment:
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
      - cluster.name=wazuh-cluster
      - network.host=0.0.0.0
      - plugins.security.disabled=false
      - plugins.security.ssl.http.enabled=true
      - plugins.security.ssl.http.pemcert_filepath=certs/wazuh-indexer.pem
      - plugins.security.ssl.http.pemkey_filepath=certs/wazuh-indexer-key.pem
      - plugins.security.ssl.http.pemtrustedcas_filepath=certs/root-ca.pem
      - plugins.security.nodes_dn=["CN=wazuh-indexer,OU=Wazuh,O=Wazuh,L=California,C=US"]
      - plugins.security.authcz.admin_dn=["CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"]
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./wazuh/indexer_conf/securityconfig:/usr/share/wazuh-indexer/securityconfig:ro
      - siem_esdata:/var/lib/wazuh-indexer
      - ./wazuh/indexer_conf/opensearch.yml:/usr/share/wazuh-indexer/opensearch.yml:ro
      - ./wazuh/indexer_conf/certs:/usr/share/wazuh-indexer/config/certs:ro
    command: /usr/share/wazuh-indexer/bin/opensearch
    networks:
      - orchestration_net

  wazuh-manager:
    image: wazuh/wazuh-manager:4.9.0
    container_name: wazuh-manager
    restart: always
    ports:
      - "1514:1514"
      - "1515:1515"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://wazuh-indexer:9200
      - WAZUH_REGISTRATION_PASSWORD=${WAZUH_API_PASSWORD}
      - INDEXER_PASSWORD=${INDEXER_PASSWORD}
      - WAZUH_API_PASSWORD=${WAZUH_API_PASSWORD}
    volumes:
      - ./wazuh/manager_etc:/var/ossec/etc
      - ./wazuh/manager_logs:/var/ossec/logs
      - ./wazuh/manager_conf/ossec.conf:/var/ossec/etc/ossec.conf:ro
    networks:
      - orchestration_net

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.9.0
    container_name: wazuh-dashboard
    hostname: wazuh-dashboard
    user: "0"
    entrypoint: >
      /bin/bash -c "
      export INDEXER_USERNAME=${INDEXER_USERNAME} &&
      export INDEXER_PASSWORD=${INDEXER_PASSWORD} &&
      export WAZUH_API_USER=${WAZUH_API_USER} &&
      export WAZUH_API_PASSWORD=${WAZUH_API_PASSWORD} &&
      /usr/share/wazuh-dashboard/bin/opensearch-dashboards --allow-root"
    environment:
      - WAZUH_API_URL=https://wazuh-manager:55000
      - WAZUH_API_USER=${WAZUH_API_USER}
      - WAZUH_API_PASSWORD=${WAZUH_API_PASSWORD}
      - INDEXER_URL=https://wazuh-indexer:9200
      - INDEXER_USERNAME=${INDEXER_USERNAME}
      - INDEXER_PASSWORD=${INDEXER_PASSWORD}
      - WAZUH_CERTIFICATE_AUTHORITIES=
      - DASHBOARD_TLS_ENABLED=true
    volumes:
      - ./wazuh/wazuh-certs/wazuh-certificates:/usr/share/wazuh-dashboard/certs:ro
      - ./wazuh/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml:ro
    networks:
      - orchestration_net

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.14.3
    container_name: filebeat
    user: root
    environment:
      - INDEXER_URL=https://wazuh-indexer:9200
      - INDEXER_USERNAME=${INDEXER_USERNAME}
      - INDEXER_PASSWORD=${INDEXER_PASSWORD}
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./wazuh/mnger_logs:/var/ossec/logs:ro
    networks:
      - orchestration_net

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wazuh-dashboard
    networks:
      - orchestration_net

volumes:
  siem_esdata:
    driver: local

networks:
  orchestration_net:
    external: true
